### ISSUE TITLE
Add geography vocabulary from MaNIS, HerpNET, ORNIS

### ISSUE THREAD

**Issue by tucotuco** [tucotuco/DwCVocabs#11]
The Gazetteer of aggregated georeferences has a large set of distinct higher geography. In anticipation of a locality service that includes these data and can resolve the higher geography to standardized values, add any new geography combinations to the LookupGeography table and resolve Canada, USA, and Mexico.

**Comment by tucotuco** [comment]
Done in commit 51f885d1a4dfc7a164abdee1bf29770b66aea03c

**Comment by dbloom** [comment]
Awesome!

**Comment by mkoo** [comment]
i want to hear more!

can anyone use the hg?
