### ISSUE TITLE
sex.csv missing "Female" with first letter upper-case

### ISSUE THREAD

**Issue by danstoner** [tucotuco/DwCVocabs#7]
Female is not present in the mapping so I believe it is getting passed through as-is ("Female" gets published rather than "female").

Sample:

http://portal.vertnet.org/o/ku/kui?id=21259

Download:

Your VertNet download file is now available for a limited time at
https://storage.googleapis.com/vn-downloads2/vertnet_female_specimens-4ca385f9dd4c425d92ed7cf9151bd394.tsv.

Query: sex:female
Matching records: 61000
Request submitted: 2016-01-14T18:49:00.376040
Request fulfilled: 2016-01-14T19:04:16.854560

**Comment by tucotuco** [comment]
That's not actually what is happening here. KUI data do not pass through a migrator, currently. They self-publish. 

As an aside, the Access database match is case-insensitive, so looking up "Female" or "female" is equivalent in the migrator, and returns "female", which is marked as a standard value.
